# Generated by Django 5.0.6 on 2026-04-30 00:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('name', models.CharField(db_column='name', max_length=200, verbose_name='name')),
                ('category', models.CharField(db_column='category', max_length=100, verbose_name='category')),
                ('address', models.CharField(blank=True, db_column='address', max_length=300, verbose_name='address')),
                ('instagram_url', models.URLField(blank=True, db_column='instagram_url', verbose_name='instagram url')),
                ('maps_url', models.URLField(blank=True, db_column='maps_url', verbose_name='maps url')),
                ('status', models.CharField(choices=[('want_to_visit', 'Want to visit'), ('visited', 'Visited'), ('favorite', 'Favorite'), ('would_not_return', 'Would not return')], db_column='status', default='want_to_visit', max_length=32, verbose_name='status')),
                ('notes', models.TextField(blank=True, db_column='notes', verbose_name='notes')),
                ('cover_photo_path', models.CharField(blank=True, db_column='cover_photo_path', max_length=500, verbose_name='cover photo path')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'db_table': 'places_place',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('visited_at', models.DateTimeField(db_column='visited_at', verbose_name='visited at')),
                ('environment_rating', models.DecimalField(blank=True, db_column='environment_rating', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='environment rating')),
                ('service_rating', models.DecimalField(blank=True, db_column='service_rating', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='service rating')),
                ('overall_rating', models.DecimalField(blank=True, db_column='overall_rating', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='overall rating')),
                ('would_return', models.BooleanField(db_column='would_return', default=True, verbose_name='would return')),
                ('general_notes', models.TextField(blank=True, db_column='general_notes', verbose_name='general notes')),
                ('photo_path', models.CharField(blank=True, db_column='photo_path', max_length=500, verbose_name='photo path')),
                ('place', models.ForeignKey(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='places.place', verbose_name='place')),
            ],
            options={
                'verbose_name': 'visit',
                'verbose_name_plural': 'visits',
                'db_table': 'places_visit',
                'ordering': ('-visited_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('name', models.CharField(db_column='name', max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('sweet', 'Sweet'), ('savory', 'Savory'), ('drink', 'Drink'), ('coffee', 'Coffee'), ('juice', 'Juice'), ('dessert', 'Dessert'), ('other', 'Other')], db_column='type', default='other', max_length=32, verbose_name='type')),
                ('rating', models.DecimalField(blank=True, db_column='rating', decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='rating')),
                ('price', models.DecimalField(blank=True, db_column='price', decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('would_order_again', models.BooleanField(db_column='would_order_again', default=True, verbose_name='would order again')),
                ('notes', models.TextField(blank=True, db_column='notes', verbose_name='notes')),
                ('photo_path', models.CharField(blank=True, db_column='photo_path', max_length=500, verbose_name='photo path')),
                ('visit', models.ForeignKey(db_column='visit_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='places.visit', verbose_name='visit')),
            ],
            options={
                'verbose_name': 'visit item',
                'verbose_name_plural': 'visit items',
                'db_table': 'places_visit_item',
                'ordering': ('-created_at',),
            },
        ),
    ]
