# Generated by Django 5.0.6 on 2026-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="cover_photo_path",
        ),
        migrations.AddField(
            model_name="place",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                db_column="cover_photo",
                null=True,
                upload_to="places/covers/",
                verbose_name="cover photo",
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="photo",
            field=models.ImageField(
                blank=True,
                db_column="photo",
                null=True,
                upload_to="visits/photos/",
                verbose_name="photo",
            ),
        ),
        migrations.AddField(
            model_name="visititem",
            name="photo",
            field=models.ImageField(
                blank=True,
                db_column="photo",
                null=True,
                upload_to="visit_items/photos/",
                verbose_name="photo",
            ),
        ),
    ]
