# Generated by Django 5.0.6 on 2026-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_remove_place_cover_photo_path_place_cover_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                db_column="latitude",
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                db_column="longitude",
                decimal_places=7,
                max_digits=10,
                null=True,
                verbose_name="longitude",
            ),
        ),
    ]
