# Generated by Django 5.0.6 on 2026-05-01 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(db_column='visited_at', db_index=True, verbose_name='visited at'),
        ),
        migrations.AlterField(
            model_name='visititem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user', 'status'], name='place_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user', 'category'], name='place_user_category_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['place', 'visited_at'], name='visit_place_visited_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['place', 'overall_rating'], name='visit_place_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='visititem',
            index=models.Index(fields=['visit', 'type'], name='visititem_visit_type_idx'),
        ),
        migrations.AddIndex(
            model_name='visititem',
            index=models.Index(fields=['visit', 'rating'], name='visititem_visit_rating_idx'),
        ),
    ]
